#!/usr/bin/env bash
INFER_PACKAGE=github.com/$INFER_AUTHOR/$INFER_NAME
INFER_GOOS="${GOOS:-$(go env GOHOSTOS)}"
INFER_GOARCH="${GOARCH:-$(go env GOHOSTARCH)}"
INFER_PLATFORM="${INFER_GOOS}/${INFER_GOARCH}"

APP_PACKAGE=${APP_PACKAGE:-$INFER_PACKAGE}
APP_IMAGE=${APP_AUTHOR}/${APP_NAME}:${APP_VERSION}
APP_IMAGE_LATEST=${APP_AUTHOR}/${APP_NAME}:latest
APP_PLATFORMS=${APP_PLATFORMS:-$INFER_PLATFORM}

LDFLAGS="\
-X main.APP_NAME=$APP_NAME \
-X main.APP_VERSION=$APP_VERSION \
-X main.BUILD_HASH=$GIT_COMMIT \
-X main.BUILD_BRANCH=$GIT_BRANCH \
-X main.BUILD_DATE=$BUILD_DATE \
-X main.BUILD_TIME=$BUILD_TIME \
"

DOCKER_WORKDIR=/go/src/$APP_PACKAGE

docker:run() {
    run docker run --rm -ti \
        -w ${DOCKER_WORKDIR} \
        -v ${APP_ROOT}:${DOCKER_WORKDIR} \
        $DOCKER_BUILD_IMAGE \
        ${@:-bash}
}
